version: "2"
services:
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "3000:3000"
        working_dir: /client/src/app
        volumes:
            - ./client:/client/src/app
        links:
            - api
        networks:
            - webappnetwork
    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
